### ISSUE TITLE
Compatibility with Nette 3.0

### ISSUE THREAD

**Issue by miloshavlicek** [ipublikuj/flysystem#4]
At this time composer.json requires Nette ~2.4

**Comment by slepic** [comment]
Actualy nette/utils ~2.4 and nette/di ~2.4...
I could also use a version that has nette/utils 2.5, I have long way to upgrade entire nette to 3.0. But I can update nette/utils to 2.5 and it would allow me to update some other packages that only depend on nette/utils.
So I would actualy greatly appreciate if you could make version with nette/utils ^2.4 and nette/di ^2.4 and then another for nette/utils ^3.0 and nette/di ^3.0. Or let me know if you would accept a PR for this, I'll happily do it....

**Comment by akadlec** [comment]
feel free to create PR

**Comment by slepic** [comment]
OH man, first of all thanks to @martenb for the fix. I have somewhat forgot about this issue, because as i already said, we have long to go up to nette 3.0, and I had other stuff to do...
Anyway I just tried to upgrade this package to 1.2.0 and it seems that there is little bug still :)
It seems that there is 
```
"nette/utils"	: "~2.4.9 || ~3.0"
```
but nette/utils has a 2.5.x version, which is not accepted by the above restriction. and by chance that is actualy what we currently have in our project. So I still can't upgrade to 1.2.x...

Changing that line to:
```
"nette/utils"	: "^2.4.9 || ~3.0"
```
would do the trick, i think... unless there was a reason for excluding 2.5.x...

**Comment by martenb** [comment]
@slepic btw v1.1.4 should work with nette/utils 2.5 just fine. acording to composer documentation:

The ~ operator is best explained by example: ~1.2 is equivalent to >=1.2 <2.0.0, while ~1.2.3 is equivalent to >=1.2.3 <1.3.0.

**Comment by slepic** [comment]
@martenb yeah, we are at 1.1.4 now. but i wanted to upgrade to 1.2 so that i dont have to deal with it when we will be moving to nette 3.0.... anyway thanks
